workflows:
  flutter-workflow:
    name: Build Flutter App
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Run tests
        script: flutter test
      - name: Build iOS
        script: flutter build ios --release --no-codesign
      - name: Build Android
        script: flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
      - build/ios/ipa/*.ipa
